# Generated by Django 4.2.11 on 2024-04-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct_api', '0002_alter_processedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('instruct', 'Instruct'), ('inpaint', 'Inpaint'), ('speech', 'Speech')], max_length=8)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('mask_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
